### ISSUE TITLE
Error: destination_table$dataset_id is not a string

### ISSUE THREAD

**Issue by caterpillars** [hadley/bigrquery#47]
Hi, 

I am brand new into big query and r world. I am trying to access some sample data from big query within R. I followed the examples here and some online, but got this error while trying to execute the query inside R. Could you please share ideas on what could be wrong? Here is the query I am trying to run:
data1<-query_exec(sql,project,dataset)

If there is any tutorial on how to use bigrquery that you are share, that would be great!

Thanks!

**Comment by caterpillars** [comment]
There seems to be something with the 'sql' I wrote. I fixed that and tried to use 'query_exec(sql, project=project)' instead of 'query_exec(project, dataset, sql, project=project)' as some website suggested. It worked for me.

**Comment by craigcitro** [comment]
hi @caterpillars -- yes, i think the issue was the args to `query_exec`. we changed & simplified them at some point recently, so it's likely an older sample wouldn't have worked.

i'm going to close this, since things seem to be working. thanks!
