### ISSUE TITLE
Response too large to return despite destination_table being set in query_exec function

### ISSUE THREAD

**Issue by tayepe** [hadley/bigrquery#59]
According to the function code allowLargeResults is set to True when the destination_table option is used. However, I've run a query with destination_table set and I still get the following error:

Error: Response too large to return. Consider setting allowLargeResults to true in your job configuration. For more details, see https://cloud.google.com/bigquery/querying-data#largequeryresults

 responseTooLarge. Response too large to return. Consider setting allowLargeResults to true in your job configuration. For more details, see https://cloud.google.com/bigquery/querying-data#largequeryresults

Any ideas why?

**Comment by craigcitro** [comment]
so i just tried and can't reproduce this -- doing something like 

    query_exec('SELECT * FROM [publicdata:samples.wikipedia]', 'myproject', destination_table = list(...))

works for me. can you post a (simplified) version of your `query_exec` call? 

of course, once the query completes, we then try to *fetch* all the rows of the large table, which isn't always a good idea. we probably want to add a `fetch_result` option here, and maybe even default to `FALSE` when a destination table is provided. WDYT @hadley?

**Comment by tayepe** [comment]
Thanks, but i've now sorted the problem. I had an ORDER BY in my query which it didn't like due to the results being too big. I've removed this and it works fine.
