### ISSUE TITLE
max_pages = Inf doesn't seem to work

### ISSUE THREAD

**Issue by FrancoisDumarest** [hadley/bigrquery#60]
nrow(query_exec("SELECT * FROM [publicdata:samples.wikipedia] limit 300000", project, max_pages = Inf))

Doesn't get me 300 000.

It seems that max_pages = Inf does'nt work.

I have been getting this issue since today.

**Comment by craigcitro** [comment]
hi @FrancoisDumarest -- can you try calling it again with `warn = TRUE` to see if it gives any extra info?

**Comment by FrancoisDumarest** [comment]
hi @craigcitro, here is what I get with the following code : nrow(query_exec("SELECT * FROM [publicdata:samples.wikipedia] limit 300000", project, max_pages = Inf, warn=TRUE))

Auto-refreshing stale OAuth token.

[1] 10000

So there isn't much extra info ...

**Comment by FrancoisDumarest** [comment]
hello, 

The probleme seemed to have dissaperaed as magically as it appeared, since I haven't changed anything, maybe it was from the project as the other people working with this project and bigrquery also experienced the same problem.

**Comment by craigcitro** [comment]
ah, there was probably a server-side issue that just got fixed. happy it's working again. :+1:
